apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blueprint-steward.fullname" . }}
  labels:
    {{- include "blueprint-steward.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
